Survey/Controllers/ExamManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Survey.Controllers
{
    public class ExamManageController : Controller
    {
        //
        // GET: /ExamManage/
        public ActionResult Index()
        {
            return View("Create");
        }

        public ActionResult Create()
        {
            return View("Create");
        }

        public ActionResult Preview()
        {
            return View();
        }
    }
}

Survey/Controllers/LoginManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Survey.Controllers
{
    public class LoginManageController : Controller
    {
        // GET: /Login/
        public ActionResult Index()
        {
            return View("Login");
        }

        public ActionResult Login()
        {
            return View();
        }

    }
}

Survey/Views/ExamManage/Create.cshtml
@{
    ViewBag.Title = "Exam Create";
}
<div class="row-fluid">
    <!-- Modal -->
    <div class="modal fade modal-wide75" id="divQsnEditorPopup" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
                    <h1 style="color: #4c4c4c; font-size: 32px; font-weight: normal; line-height: 35px;">Question Editor</h1>
                </div>
                <div class="modal-body">
                    
                    <!-- ko with: question() -->

                    <!-- ko if: $data.questionType === 'MultipleChoice' -->
                    <div class="row-fluid" data-bind="template: { name: 'tmplEditorMultipleChoice', data: $data }" ></div>
                    <!-- /ko -->

                    <!-- ko if: $data.questionType === 'SingleChoice' -->
                    <div class="row-fluid" data-bind="template: { name: 'tmplEditorSingleChoice', data: $data }" ></div>
                    <!-- /ko --> 
        
                    <!-- ko if: $data.questionType === 'Descriptive' -->
                    <div class="row-fluid" data-bind="template: { name: 'tmplEditorDescriptive', data: $data }" ></div>
                    <!-- /ko -->
                    
                    <!-- ko if: $data.questionType === 'ComboBox' -->
                    <div class="row-fluid" data-bind="template: { name: 'tmplEditorComboBox', data: $data }"></div>
                    <!-- /ko -->
        
                    <!-- /ko -->                    

                </div>
            </div>
        </div>
    </div>
</div>


@*<div class="row-fluid">Name of The Exam</div>*@
<div class="row-fluid">
    <div class="span3">        
        <div id="divQuestionType" class="list-group divQuestionType" data-bind="with: questionTypes">
            <!-- ko foreach: types -->
            <a href="#" class="list-group-item" data-bind="appendContent: nameText, attr: { qsnType : type}">
                <i data-bind="attr: { class : iconSyle}"></i>
            </a>
            <!-- /ko -->
            
            
            <a class="btn btn-large" title="Edit" data-bind="click: $root.previewExam" style="margin-top: 20px; float: right">
                <span class="icon-pencil icon-white"></span>
                Preview Exam
            </a>
        </div>
    </div>

    <div id="divQuestions" class="container-fluid span9 divQuestions">
        <div data-bind="style: { display: hasAnyQuestion() ? 'none' : 'block'}" style="background-color: #F5F5F5; padding: 35px">
            <div class="wrap-title">
                <h1>
                    <small style="left: 0px; right: 0px">Drop question types, and move up/down to change its position</small>
                </h1>
            </div>
        </div>  
        
        <!-- ko foreach: questions() -->

        <!-- ko if: $data.questionType === 'MultipleChoice' -->
        <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplMultipleChoice', data: $data }, attr: {id: guidId}" ></div>
        <!-- /ko -->

        <!-- ko if: $data.questionType === 'SingleChoice' -->
        <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplSingleChoice', data: $data }, attr: {id: guidId}" ></div>
        <!-- /ko --> 
        
        <!-- ko if: $data.questionType === 'Descriptive' -->
        <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplDescriptive', data: $data }, attr: {id: guidId}" ></div>
        <!-- /ko -->
        
        <!-- ko if: $data.questionType === 'ComboBox' -->
        <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplComboBox', data: $data }, attr: {id: guidId}"></div>
        <!-- /ko -->
        
        <!-- /ko -->
    </div>
</div>

@section scripts{
    @Html.Partial("~/Views/ExamManage/QuestionEditorTmpl.cshtml")
    @Html.Partial("~/Views/ExamManage/QuestionTmpl.cshtml")
    <script src="~/Scripts/Shared/common.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.questionType.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.singleChoice.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.multipleChoice.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.descriptive.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.comboBox.js"></script>
    <script  type='text/javascript' src= "@Url.Content("~/Scripts/ExamManage/create.js")"></script> 
}

Survey/Views/ExamManage/Preview.cshtml
@{
    ViewBag.Title = "Exam Preview";
}

<div class="row-fluid">
    <div class="span12">
        <div id="divQuestions" class="container-fluid span10 divQuestions" style=" margin: 0 auto !important; float: none !important;">
            <div data-bind="style: { display: hasAnyQuestion() ? 'none' : 'block'}">
                <div class="wrap-title">
                    <h1>
                        <small style="left: 0px; right: 0px">No Question for the exam</small>
                    </h1>
                </div>
            </div>  
        
            <!-- ko foreach: questions() -->

            <!-- ko if: $data.questionType() === 'MultipleChoice' -->
            <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplMultipleChoice', data: $data }" ></div>
            <!-- /ko -->

            <!-- ko if: $data.questionType() === 'SingleChoice' -->
            <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplSingleChoice', data: $data }" ></div>
            <!-- /ko --> 
        
            <!-- ko if: $data.questionType() === 'Descriptive' -->
            <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplDescriptive', data: $data }" ></div>
            <!-- /ko -->
        
            <!-- ko if: $data.questionType() === 'ComboBox' -->
            <div class="row-fluid divQuestion" data-bind="template: { name: 'tmplComboBox', data: $data }"></div>
            <!-- /ko -->

            <!-- /ko -->
        </div>      
    </div>
</div>

@section scripts{
    @Html.Partial("~/Views/ExamManage/PreviewQuestionTmpl.cshtml")
    <script src="~/Scripts/Shared/common.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.questionType.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.singleChoice.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.multipleChoice.js"></script>
    <script src="~/Scripts/Shared/Vms/vm.qsn.descriptive.js"></script>
    <script  type='text/javascript' src= "@Url.Content("~/Scripts/ExamManage/preview.js")"></script> 
}

Survey/Views/ExamManage/PreviewQuestionTmpl.cshtml
<!-- tmpl Single Choice-->
<script type="text/html" id="tmplSingleChoice">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <div class="btn-group divEditPanel">
            <a class="btn" title="Reset" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Reset
            </a>
        </div>
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <br/>
    </div>
    <!-- ko foreach: options -->
    <div class="span10">
        <label>
            <input type="radio" />
            <span data-bind="text: title"></span>                
        </label>
    </div>
    <!-- /ko -->
</script>


<!-- tmpl Multiple Choice-->
<script type="text/html" id="tmplMultipleChoice">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Reset" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Reset
            </a>
        </div>
        <br/>
    </div>
    <!-- ko foreach: options -->
    <div class="span10">
        <label class="checkbox">
            <input type="checkbox" />
            <span data-bind="text: title"></span>                
        </label>
    </div>
    <!-- /ko -->
</script>


<!-- tmpl Descriptive-->
<script type="text/html" id="tmplDescriptive">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Reset" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Reset
            </a>
        </div>
        <br/>
    </div>
    <div class="span10">
        <div>
            <textarea></textarea>                    
        </div>
    </div>
</script>


<!-- tmpl Single Choice-->
<script type="text/html" id="tmplComboBox">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <div class="btn-group divEditPanel">
            <a class="btn" title="Reset" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Reset
            </a>
        </div>
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <br />
    </div>
    <div class="span10">
        <select class="span6" data-bind="options: options,
                                        optionsText: 'title',
                                        optionsValue: 'value',
                                        optionsCaption: '--- Please Select ---'"></select>
    </div>
</script>

Survey/Views/ExamManage/QuestionTmpl.cshtml
<!-- tmpl Single Choice-->
<script type="text/html" id="tmplSingleChoice">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Edit" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Edit
            </a>
            <a class="btn" title="Delete" data-bind="click: $root.confirmQsnToDelete">
                <span class="icon-remove icon-white"></span>
                Delete
            </a>
        </div>
        <br/>
    </div>
    <!-- ko foreach: options -->
    <div class="span10">
        <label>
            <input type="radio" />
            <span data-bind="text: title"></span>                
        </label>
    </div>
    <!-- /ko -->
</script>


<!-- tmpl Multiple Choice-->
<script type="text/html" id="tmplMultipleChoice">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Edit" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Edit
            </a>
            <a class="btn" title="Delete" data-bind="click: $root.confirmQsnToDelete">
                <span class="icon-remove icon-white"></span>
                Delete
            </a>
        </div>
        <br/>
    </div>
    <!-- ko foreach: options -->
    <div class="span10">
        <label class="checkbox">
            <input type="checkbox" />
            <span data-bind="text: title"></span>                
        </label>
    </div>
    <!-- /ko -->
</script>


<!-- tmpl Descriptive-->
<script type="text/html" id="tmplDescriptive">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Edit" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Edit
            </a>
            <a class="btn" title="Delete" data-bind="click: $root.confirmQsnToDelete">
                <span class="icon-remove icon-white"></span>
                Delete
            </a>
        </div>
        <br/>
    </div>
    <div class="span10">
        <div>
            <textarea></textarea>                    
        </div>
    </div>
</script>



<!-- tmpl ComboBox-->
<script type="text/html" id="tmplComboBox">
    <div class="span12" style="margin-bottom: 20px;" data-bind="appendContent: title">
        <h2 class="btn" data-bind="text: ($index() + 1)"></h2>
        <div class="btn-group divEditPanel">
            <a class="btn" title="Edit" data-bind="click: $root.showQsnToEdit">
                <span class="icon-pencil icon-white"></span>
                Edit
            </a>
            <a class="btn" title="Delete" data-bind="click: $root.confirmQsnToDelete">
                <span class="icon-remove icon-white"></span>
                Delete
            </a>
        </div>
        <br />
    </div>
    <div class="span10">
        <select class="span6" data-bind="options: options,
                                        optionsText: 'title',
                                        optionsValue: 'value',
                                        optionsCaption: '--- Please Select ---'"></select>
    </div>
</script>

Survey/Views/LoginManage/Login.cshtml
@{
    ViewBag.Title = "login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div id="loader"><img src="~/Views/Shared/img/loader.gif"/></div>
       
<div class="login">
    <div class="page-header">
        <div class="icon">
            <span class="ico-arrow-right"></span>
        </div>
        <h1>Login <small>METRO STYLE ADMIN PANEL</small></h1>
    </div>        
    <div class="row-fluid">
        <div class="row-form">
            <div class="span12">
                <input type="text" name="login" placeholder="login" value="admin"/>
            </div>
        </div>
        <div class="row-form">
            <div class="span12">
                <input type="password" name="password" placeholder="password" value="admin"/>
            </div>            
        </div>
        <div class="row-form">
            <div class="span12">
                <input type="checkbox"/> Keep me signed in
            </div>
        </div>
        <div class="row-form">
            <div class="span12">
                <a class="btn" href="@Url.Action("Index", "ExamManage")">
                    Sign in <span class="icon-arrow-next icon-white"></span>
                </a>
            </div>                
        </div>
    </div>
</div>

Survey/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from aqvatarius.com/themes/aries/ by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 06 Sep 2013 22:19:40 GMT -->
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />    
        <!--[if gt IE 8]>
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />        
        <![endif]-->                
        <title>Aries - Metro Style Admin Panel</title>
        <link rel="icon" type="image/ico" href="/favicon.ico"/>
        <link href="~/Content/css/cleditor/cleditor.css" rel="stylesheet" />
        <link href="~/Content/css/stylesheets.css" rel="stylesheet" type="text/css" />
        <!--[if lte IE 7]>
            <link href="~/Content/css/ie.css" rel="stylesheet" type="text/css" />
            <script type='text/javascript' src='~/Content/js/plugins/other/lte-ie7.js'> </script>
        <![endif]-->    
    </head>
    <body>    
        <div id="loader"><img src="~/Content/img/loader.gif"/></div>
        <div class="wrapper">
        
            <div class="sidebar">
                <div class="top">
                    <a href="index-2.html" class="logo"></a>
                    <div class="search">
                        <div class="input-prepend">
                            <span class="add-on orange"><span class="icon-search icon-white"></span></span>
                            <input type="text" placeholder="search..."/>                                                      
                        </div>            
                    </div>
                </div>
                <div class="nContainer">
                    <ul class="navigation">         
                        <li class="active"><a href="@Url.Action("Index", "ExamManage")" class="blgreen">Exam</a></li>
                    </ul>
                    <a class="close">
                        <span class="ico-remove"></span>
                    </a>
                </div>
                <div class="widget">
                    <div class="datepicker"></div>
                </div>           
            </div>
        
            <div class="body">
            
                <ul class="navigation">

                    <li>
                        <div class="user">
                            <img src="~/Content/img/examples/users/dmitry_m.jpg" align="left"/>
                            <a href="#" class="name">
                                <span>Dmitry Ivaniuk</span>
                                <span class="sm">Administrator</span>
                            </a>
                        </div>
                    </li>
                     
                
                    <li>
                        <div class="buttons">
                            <div class="sbutton green navButton">
                                <a href="#"><span class="ico-align-justify"></span></a>
                            </div>
                            <div class="sbutton blue">
                                <a href="#"><span class="ico-cogs"></span></a>
                                <div class="popup">
                                    <div class="arrow"></div>
                                    <div class="row-fluid">
                                        <div class="row-form">
                                            <div class="span12"><strong>SETTINGS</strong></div>
                                        </div>                                    
                                        <div class="row-form">
                                            <div class="span4">Navigation:</div>
                                            <div class="span8">
                                                <label><input type="radio" class="cNav" name="cNavButton" value="default"/> Default</label>
                                                <label><input type="radio" class="cNav" name="cNavButton" value="bordered"/> Bordered</label>
                                            </div>
                                        </div>
                                        <div class="row-form">
                                            <div class="span4">Nav color:</div>
                                            <div class="span8">
                                                <div class="cNavC">
                                                    <span class="color_1" name="cNavButColor"></span>
                                                    <span class="color_2" name="cNavButColor"></span>
                                                    <span class="color_3" name="cNavButColor"></span>
                                                    <span class="color_4" name="cNavButColor"></span>
                                                    <span class="color_5" name="cNavButColor"></span>
                                                    <span class="color_6" name="cNavButColor"></span>
                                                    <span class="color_7" name="cNavButColor"></span>
                                                    <span class="color_8" name="cNavButColor"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row-form">
                                            <div class="span4">Top navigation:</div>
                                            <div class="span8">
                                                <label><input type="radio" class="cTopNavH" name="cTopNavHide" value="show"/> Show</label>
                                                <label><input type="radio" class="cTopNavH" name="cTopNavHide" value="hide"/> Hide</label>
                                            </div>
                                        </div> 
                                        <div class="row-form">
                                            <div class="span4">Content:</div>
                                            <div class="span8">
                                                <label><input type="radio" class="cCont" name="cContent" value=""/> Responsive</label>
                                                <label><input type="radio" class="cCont" name="cContent" value="fixed"/> Fixed</label>
                                            </div>
                                        </div>                                    
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </li>                
                </ul>
            
            
                <div class="content">
                
                    <div class="page-header">
                        <div class="wrap-title">
                            <h1>Dashboard <small>METRO STYLE ADMIN PANEL</small></h1>
                        </div>
                        <ul class="breadcrumb">
                            <li class="active">Home</li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                    @RenderBody()
                </div>
            
            </div>
        
        </div>
    
        <div class="dialog" id="source" style="display: none;" title="Source"></div>
    
        <div id="fcAddEvent" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="fcAddEventLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="fcAddEventLabel">Add new event</h3>
            </div>
            <div class="modal-body">
                <div class="row-fluid">
                    <div class="span3">Title:</div>
                    <div class="span9"><input type="text" id="fcAddEventTitle"/></div>
                </div>
            </div>
            <div class="modal-footer">            
                <button class="btn btn-primary" id="fcAddEventButton">Add</button>            
            </div>
        </div>    
        

        <script type='text/javascript' src='~/Scripts/jquery-2.1.0.min.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/jquery-ui-1.10.3.custom.min.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/jquery-migrate-1.2.1.min.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/globalize.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/other/excanvas.js'> </script>
    
        <script type='text/javascript' src='~/Content/js/plugins/other/jquery.mousewheel.min.js'> </script>
        
        <script type='text/javascript' src='~/Content/js/plugins/bootstrap/bootstrap.min.js'> </script>
        <script src="~/Content/js/plugins/bootstrapModalPopover/bootstrap-modal-popover.js"></script>

        <script type='text/javascript' src='~/Content/js/plugins/cookies/jquery.cookies.2.2.0.min.js'> </script>    
    
        <script type='text/javascript' src='~/Content/js/plugins/jflot/jquery.flot.js'> </script>    
        <script type='text/javascript' src='~/Content/js/plugins/jflot/jquery.flot.stack.js'> </script>    
        <script type='text/javascript' src='~/Content/js/plugins/jflot/jquery.flot.pie.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/jflot/jquery.flot.resize.js'> </script>
    
        <script type='text/javascript' src='~/Content/js/plugins/epiechart/jquery.easy-pie-chart.js'> </script>    
        <script type='text/javascript' src='~/Content/js/plugins/sparklines/jquery.sparkline.min.js'> </script>        
    
        <script type='text/javascript' src='~/Content/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js'> </script>
    
        <script type='text/javascript' src='~/Content/js/plugins/uniform/jquery.uniform.min.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/cleditor/jquery.cleditor.js'></script> 
        <script type='text/javascript' src='~/Content/js/plugins/fullcalendar/fullcalendar.min.js'> </script>
    
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/XRegExp.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shCore.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushXml.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushJScript.js'> </script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushCss.js'> </script>    
    
        <script type='text/javascript' src='~/Content/js/plugins.js'> </script>
        <script type='text/javascript' src='~/Content/js/charts.js'> </script>  
        <script type='text/javascript' src='~/Content/js/actions.js'> </script>
        
        <script src="~/Scripts/json2.min.js"></script>
        <script src="~/Scripts/amplify.min.js"></script>

        <script src="~/Scripts/knockout-3.1.0.js"></script>
        <script src="~/Scripts/knockout.validation.js"></script>
        <script src="~/Scripts/knockout.mapping-latest.js"></script>
        
        <script src="~/Scripts/infuser.min.js"></script>
        <script src="~/Scripts/TrafficCop.min.js"></script>
        <script src="~/Scripts/koExternalTemplateEngine.min.js"></script>

        @RenderSection("scripts", required: false)   
    </body>

    <!-- Mirrored from aqvatarius.com/themes/aries/ by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 06 Sep 2013 22:21:46 GMT -->
</html>

Survey/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from aqvatarius.com/themes/aries/login.html by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 06 Sep 2013 22:23:23 GMT -->
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />    
        <!--[if gt IE 8]>
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />        
        <![endif]-->                
        <title>Login - Aries Premium Admin Template</title>
        <link rel="icon" type="image/ico" href="~/favicon.ico"/>
    
        <link href="~/Content/css/stylesheets.css" rel="stylesheet" type="text/css" />
        <!--[if lt IE 10]>
            <link href="~/Content/css/ie.css" rel="stylesheet" type="text/css" />
        <![endif]-->           
        <!--[if lte IE 7]>
            <script type='text/javascript' src='~/Content/js/plugins/other/lte-ie7.js'></script>
        <![endif]-->    
        <script type='text/javascript' src='~/Scripts/jquery-2.1.0.min.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/jquery-ui-1.10.3.custom.min.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/jquery-migrate-1.2.1.min.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/jquery/globalize.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/other/excanvas.js'></script>
    
        <script type='text/javascript' src='~/Content/js/plugins/other/jquery.mousewheel.min.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/bootstrap/bootstrap.min.js'></script>
        <script type='text/javascript' src="'~/Content/js/plugins/uniform/jquery.uniform.min.js"></script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/XRegExp.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shCore.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushXml.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushJScript.js'></script>
        <script type='text/javascript' src='~/Content/js/plugins/shbrush/shBrushCss.js'></script>    
    
        <script type='text/javascript' src='~/Content/js/plugins.js'></script>
        <script type='text/javascript' src='~/Content/js/charts.js'></script>
        <script type='text/javascript' src='~/Content/js/actions.js'></script>

        <script src="~/Scripts/json2.min.js"></script>
        <script src="~/Scripts/amplify.min.js"></script>
        <script src="~/Scripts/knockout-3.1.0.js"></script>
    
    </head>
    <body>  
        @RenderBody()      
    </body>

    <!-- Mirrored from aqvatarius.com/themes/aries/login.html by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 06 Sep 2013 22:23:23 GMT -->
</html>